# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReSampleWin.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReSampleWin(object):
    def setupUi(self, ReSampleWin):
        ReSampleWin.setObjectName("ReSampleWin")
        ReSampleWin.resize(405, 311)
        ReSampleWin.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(ReSampleWin)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(ReSampleWin)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(ReSampleWin)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rBtn_NN = QtWidgets.QRadioButton(self.groupBox)
        self.rBtn_NN.setChecked(True)
        self.rBtn_NN.setObjectName("rBtn_NN")
        self.horizontalLayout.addWidget(self.rBtn_NN)
        self.rBtn_Liner = QtWidgets.QRadioButton(self.groupBox)
        self.rBtn_Liner.setObjectName("rBtn_Liner")
        self.horizontalLayout.addWidget(self.rBtn_Liner)
        self.rBtn_Cube = QtWidgets.QRadioButton(self.groupBox)
        self.rBtn_Cube.setObjectName("rBtn_Cube")
        self.horizontalLayout.addWidget(self.rBtn_Cube)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(ReSampleWin)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.LinEdit_TWidth = QtWidgets.QLineEdit(self.groupBox_2)
        self.LinEdit_TWidth.setObjectName("LinEdit_TWidth")
        self.gridLayout_2.addWidget(self.LinEdit_TWidth, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 2, 1, 1)
        self.LinEdit_THeightRatio = QtWidgets.QLineEdit(self.groupBox_2)
        self.LinEdit_THeightRatio.setObjectName("LinEdit_THeightRatio")
        self.gridLayout_2.addWidget(self.LinEdit_THeightRatio, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.LinEdit_THeight = QtWidgets.QLineEdit(self.groupBox_2)
        self.LinEdit_THeight.setObjectName("LinEdit_THeight")
        self.gridLayout_2.addWidget(self.LinEdit_THeight, 1, 3, 1, 1)
        self.LinEdit_TWidthRatio = QtWidgets.QLineEdit(self.groupBox_2)
        self.LinEdit_TWidthRatio.setObjectName("LinEdit_TWidthRatio")
        self.gridLayout_2.addWidget(self.LinEdit_TWidthRatio, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.Label_OWidth = QtWidgets.QLabel(self.groupBox_2)
        self.Label_OWidth.setText("")
        self.Label_OWidth.setObjectName("Label_OWidth")
        self.gridLayout_2.addWidget(self.Label_OWidth, 0, 1, 1, 1)
        self.Label_OHeight = QtWidgets.QLabel(self.groupBox_2)
        self.Label_OHeight.setText("")
        self.Label_OHeight.setObjectName("Label_OHeight")
        self.gridLayout_2.addWidget(self.Label_OHeight, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)

        self.retranslateUi(ReSampleWin)
        self.buttonBox.accepted.connect(ReSampleWin.accept)
        self.buttonBox.rejected.connect(ReSampleWin.reject)
        QtCore.QMetaObject.connectSlotsByName(ReSampleWin)
        ReSampleWin.setTabOrder(self.LinEdit_TWidth, self.LinEdit_THeight)
        ReSampleWin.setTabOrder(self.LinEdit_THeight, self.LinEdit_TWidthRatio)
        ReSampleWin.setTabOrder(self.LinEdit_TWidthRatio, self.LinEdit_THeightRatio)
        ReSampleWin.setTabOrder(self.LinEdit_THeightRatio, self.rBtn_NN)
        ReSampleWin.setTabOrder(self.rBtn_NN, self.rBtn_Liner)
        ReSampleWin.setTabOrder(self.rBtn_Liner, self.rBtn_Cube)

    def retranslateUi(self, ReSampleWin):
        _translate = QtCore.QCoreApplication.translate
        ReSampleWin.setWindowTitle(_translate("ReSampleWin", "重采样"))
        self.groupBox.setTitle(_translate("ReSampleWin", "重采样方法"))
        self.rBtn_NN.setText(_translate("ReSampleWin", "最近邻"))
        self.rBtn_Liner.setText(_translate("ReSampleWin", "双线性"))
        self.rBtn_Cube.setText(_translate("ReSampleWin", "三次立方"))
        self.groupBox_2.setTitle(_translate("ReSampleWin", "重采样参数"))
        self.label_2.setText(_translate("ReSampleWin", "目标高："))
        self.label_3.setText(_translate("ReSampleWin", "目标宽比例："))
        self.label_4.setText(_translate("ReSampleWin", "目标高比例："))
        self.label.setText(_translate("ReSampleWin", "目标宽："))
        self.label_5.setText(_translate("ReSampleWin", "原始宽："))
        self.label_6.setText(_translate("ReSampleWin", "原始高："))
